<x-layouts.app
    title="Privacy &amp; Cookies — PHP, evolved"
    description="What this site stores: essential cookies and browser local storage only — no tracking and no advertising.">

  <section class="section hero-glow" style="padding-block:clamp(48px,6vw,80px) clamp(24px,3vw,36px);">
    <div class="container center anim-in">
      <p class="eyebrow" style="justify-content:center;">Privacy</p>
      <h1 style="max-width:20ch;margin-inline:auto;">Privacy &amp; cookies</h1>
      <p class="lead mx-auto mt-md" style="max-width:56ch;">
        This site keeps things minimal: essential cookies to operate, and browser storage for your
        preferences. No tracking, no advertising, no third-party analytics.
      </p>
    </div>
  </section>

  <section class="section" style="padding-block:clamp(16px,3vw,32px);">
    <div class="container doc-body" style="max-width:74ch;">

      <h2>Cookies</h2>
      <p>
        We set only <strong>essential</strong> cookies. They are required for the site to work and
        cannot be switched off through a preference:
      </p>
      <ul>
        <li><strong>Session cookie</strong> — identifies your browsing session (security, form state).</li>
        <li><strong>CSRF token</strong> — protects forms against cross-site request forgery.</li>
      </ul>
      <p>We do not use advertising, profiling, or analytics cookies, and we do not sell data.</p>

      <h2>Local storage</h2>
      <p>
        Some features keep data in your browser's local storage. It stays on your device and is never
        sent to us unless the feature needs it:
      </p>
      <ul>
        <li><code>php-theme</code> — your light/dark theme choice.</li>
        <li><code>php-rebrand:assistant-size</code> — the AI assistant panel size.</li>
        <li><code>php-rebrand:assistant-history</code> — your AI assistant conversation, so it survives a reload.</li>
        <li><code>php-rebrand:cookie-consent</code> — your choice on this banner.</li>
      </ul>

      <h2>Ask AI assistant</h2>
      <p>
        When you ask the assistant a question, the question and the excerpts of the manual pages used
        to answer it are sent to <a href="https://openrouter.ai/" target="_blank" rel="noreferrer">OpenRouter</a>
        and the language model it routes to, so it can compose the answer. Do not include personal or
        confidential information in a question. Answers are generated by a free AI model and may be
        inaccurate — always check the linked manual pages. Your conversation is stored only in your
        browser; the <em>Clear</em> button in the assistant removes it.
      </p>

      <h2>Your choices</h2>
      <p>
        You can clear this site's cookies and local storage at any time through your browser's
        settings ("Clear site data"), or by using the <em>Clear</em> button in the AI assistant. Doing
        so removes your theme, assistant history, and consent choice.
      </p>

      <h2>Content</h2>
      <p>
        The manual, news, and release information are derived from the official PHP project sources
        and remain subject to their original licenses. See the
        <a href="/get-involved" wire:navigate>Get involved</a> page and the project README for details.
      </p>

      <p class="meta mt-lg">Last updated: September 2026.</p>
    </div>
  </section>
</x-layouts.app>
